name: Rynair Data Scraper

on:
  schedule:
    - cron: '0 */2 * * *' # co 2h
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run scraper
        run: python script.py
      - name: Commit CSV
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update CSV"
          branch: main
          file_pattern: ryanair_nov_full_async.csv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
